# =========================
# Quotas for 3 projects: TTDMST, DVS, TTCNTT
# =========================

# -------------------------
# TTDMST (2420b0c0a5ae4f738e291d9462eecc1c)
# -------------------------
apiVersion: compute.openstack.crossplane.io/v1alpha1
kind: QuotasetV2
metadata:
  name: qpack-compute-ttdmst
  namespace: crossplane-system
  labels: {policy: baseline}
  annotations:
    infra.allow-delete: "false"
spec:
  deletionPolicy: Orphan
  managementPolicies: ["Observe","Create","Update"]
  providerConfigRef: { name: provider-openstack-config }
  forProvider:
    region: RegionOne
    projectId: 2420b0c0a5ae4f738e291d9462eecc1c
    instances: 1977
    cores: 1977
    ram: 6939648 # MiB (6777 GiB * 1024)
    serverGroups: 50
    serverGroupMembers: 500

---
apiVersion: networking.openstack.crossplane.io/v1alpha1
kind: QuotaV2
metadata:
  name: qpack-network-ttdmst
  namespace: crossplane-system
  labels: {policy: baseline}
  annotations:
    infra.allow-delete: "false"
spec:
  deletionPolicy: Orphan
  managementPolicies: ["Observe","Create","Update"]
  providerConfigRef: { name: provider-openstack-config }
  forProvider:
    region: RegionOne
    projectId: 2420b0c0a5ae4f738e291d9462eecc1c
    network: 200
    subnet: 400
    port: 20000
    router: 200
    floatingip: 1000
    securityGroup: 200
    securityGroupRule: 5000

---
apiVersion: blockstorage.openstack.crossplane.io/v1alpha1
kind: QuotasetV3
metadata:
  name: qpack-block-ttdmst
  namespace: crossplane-system
  labels: {policy: baseline}
  annotations:
    infra.allow-delete: "false"
spec:
  deletionPolicy: Orphan
  managementPolicies: ["Observe","Create","Update"]
  providerConfigRef: { name: provider-openstack-config }
  forProvider:
    region: RegionOne
    projectId: 2420b0c0a5ae4f738e291d9462eecc1c
    volumes: 2000
    snapshots: 2000
    gigabytes: 158493
    backups: 500
    backupGigabytes: 100000

---
apiVersion: lb.openstack.crossplane.io/v1alpha1
kind: QuotaV2
metadata:
  name: qpack-lb-ttdmst
  namespace: crossplane-system
  labels: {policy: baseline}
  annotations:
    infra.allow-delete: "false"
spec:
  deletionPolicy: Orphan
  managementPolicies: ["Observe","Create","Update"]
  providerConfigRef: { name: provider-openstack-config }
  forProvider:
    region: RegionOne
    projectId: 2420b0c0a5ae4f738e291d9462eecc1c
    loadbalancer: 200
    listener: 400
    pool: 400
    member: 4000

# -------------------------
# DVS (ded5af59b056479eb7af86c91c094d5c)
# -------------------------
---
apiVersion: compute.openstack.crossplane.io/v1alpha1
kind: QuotasetV2
metadata:
  name: qpack-compute-dvs
  namespace: crossplane-system
  labels: {policy: baseline}
  annotations:
    infra.allow-delete: "false"
spec:
  deletionPolicy: Orphan
  managementPolicies: ["Observe","Create","Update"]
  providerConfigRef: { name: provider-openstack-config }
  forProvider:
    region: RegionOne
    projectId: ded5af59b056479eb7af86c91c094d5c
    instances: 2644
    cores: 2644
    ram: 5350400 # MiB (5225 GiB * 1024)
    serverGroups: 50
    serverGroupMembers: 500

---
apiVersion: networking.openstack.crossplane.io/v1alpha1
kind: QuotaV2
metadata:
  name: qpack-network-dvs
  namespace: crossplane-system
  labels: {policy: baseline}
  annotations:
    infra.allow-delete: "false"
spec:
  deletionPolicy: Orphan
  managementPolicies: ["Observe","Create","Update"]
  providerConfigRef: { name: provider-openstack-config }
  forProvider:
    region: RegionOne
    projectId: ded5af59b056479eb7af86c91c094d5c
    network: 200
    subnet: 400
    port: 20000
    router: 200
    floatingip: 1000
    securityGroup: 200
    securityGroupRule: 5000

---
apiVersion: blockstorage.openstack.crossplane.io/v1alpha1
kind: QuotasetV3
metadata:
  name: qpack-block-dvs
  namespace: crossplane-system
  labels: {policy: baseline}
  annotations:
    infra.allow-delete: "false"
spec:
  deletionPolicy: Orphan
  managementPolicies: ["Observe","Create","Update"]
  providerConfigRef: { name: provider-openstack-config }
  forProvider:
    region: RegionOne
    projectId: ded5af59b056479eb7af86c91c094d5c
    volumes: 2000
    snapshots: 2000
    gigabytes: 247309
    backups: 500
    backupGigabytes: 100000

---
apiVersion: lb.openstack.crossplane.io/v1alpha1
kind: QuotaV2
metadata:
  name: qpack-lb-dvs
  namespace: crossplane-system
  labels: {policy: baseline}
  annotations:
    infra.allow-delete: "false"
spec:
  deletionPolicy: Orphan
  managementPolicies: ["Observe","Create","Update"]
  providerConfigRef: { name: provider-openstack-config }
  forProvider:
    region: RegionOne
    projectId: ded5af59b056479eb7af86c91c094d5c
    loadbalancer: 200
    listener: 400
    pool: 400
    member: 4000

# -------------------------
# TTCNTT (7c9aaa5c45cb40fa89aa9ebbe5a8d9fb)
# -------------------------
---
apiVersion: compute.openstack.crossplane.io/v1alpha1
kind: QuotasetV2
metadata:
  name: qpack-compute-ttcntt
  namespace: crossplane-system
  labels: {policy: baseline}
  annotations:
    infra.allow-delete: "false"
spec:
  deletionPolicy: Orphan
  managementPolicies: ["Observe","Create","Update"]
  providerConfigRef: { name: provider-openstack-config }
  forProvider:
    region: RegionOne
    projectId: 7c9aaa5c45cb40fa89aa9ebbe5a8d9fb
    instances: 400
    cores: 400
    ram: 2560000 # MiB (2500 GiB * 1024)
    serverGroups: 50
    serverGroupMembers: 500

---
apiVersion: networking.openstack.crossplane.io/v1alpha1
kind: QuotaV2
metadata:
  name: qpack-network-ttcntt
  namespace: crossplane-system
  labels: {policy: baseline}
  annotations:
    infra.allow-delete: "false"
spec:
  deletionPolicy: Orphan
  managementPolicies: ["Observe","Create","Update"]
  providerConfigRef: { name: provider-openstack-config }
  forProvider:
    region: RegionOne
    projectId: 7c9aaa5c45cb40fa89aa9ebbe5a8d9fb
    network: 200
    subnet: 400
    port: 20000
    router: 200
    floatingip: 1000
    securityGroup: 200
    securityGroupRule: 5000

---
apiVersion: blockstorage.openstack.crossplane.io/v1alpha1
kind: QuotasetV3
metadata:
  name: qpack-block-ttcntt
  namespace: crossplane-system
  labels: {policy: baseline}
  annotations:
    infra.allow-delete: "false"
spec:
  deletionPolicy: Orphan
  managementPolicies: ["Observe","Create","Update"]
  providerConfigRef: { name: provider-openstack-config }
  forProvider:
    region: RegionOne
    projectId: 7c9aaa5c45cb40fa89aa9ebbe5a8d9fb
    volumes: 2000
    snapshots: 2000
    gigabytes: 200000
    backups: 500
    backupGigabytes: 100000

---
apiVersion: lb.openstack.crossplane.io/v1alpha1
kind: QuotaV2
metadata:
  name: qpack-lb-ttcntt
  namespace: crossplane-system
  labels: {policy: baseline}
  annotations:
    infra.allow-delete: "false"
spec:
  deletionPolicy: Orphan
  managementPolicies: ["Observe","Create","Update"]
  providerConfigRef: { name: provider-openstack-config }
  forProvider:
    region: RegionOne
    projectId: 7c9aaa5c45cb40fa89aa9ebbe5a8d9fb
    loadbalancer: 200
    listener: 400
    pool: 400
    member: 4000
