apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-nginx-html
  namespace: demo
data:
  index.html: |
    <!doctype html>
    <html>
      <head><meta charset="utf-8"><title>Nginx Demo</title></head>
      <body style="font-family:Arial">
        <h1>NGINX DEMO via ArgoCD</h1>
        <p>Updated from Git at: 2025-12-26</p>
      </body>
    </html>
