apiVersion: v1
kind: Service
metadata:
  name: demo-nginx
  namespace: demo
spec:
  type: NodePort
  selector:
    app: demo-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 32530
